version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - automotive-network

  offer-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: offer-service
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=192.168.2.97\\MSSQLSERVER;Initial Catalog=AICodeChallenge2025;User ID=remote_user;Password=xi(w1rMbvhMA;TrustServerCertificate=True
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      - rabbitmq
    networks:
      - automotive-network

networks:
  automotive-network:
    driver: bridge